icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#1e1e1e"
idle_fg = "#a7a7a7"
info_bg = "#afc4db"
info_fg = "#1e1e1e"
good_bg = "#8f9d6a"
good_fg = "#1e1e1e"
warning_bg = "#f9ee98"
warning_fg = "#1e1e1e"
critical_bg = "#cf6a4c"
critical_fg = "#1e1e1e"
# The rest of the theme settings are left at default.




[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 20



[[block]]
block = "net"
device = "enp0s31f6"
ssid = true
ip = true
interval = 5

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = true
interval = 5


[[block]]
block = "pacman"
interval = 10

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m} {15m}"

[[block]]
block = "cpu"
interval = 5
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"
device = "BAT1"
interval = 10
format = "{percentage}% {time}"


[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"



# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Twilight by David Hart (https://github.com/hartbit)
